name = "MyVVPackage"
uuid = "e32a011c-862e-4cf6-b187-8e583d1bb9b2"
authors = ["Ewout39 <ewout.venstermans@student.kuleuven.be>"]
version = "0.1.0"

[deps]
PowerModelsDistribution = "d7431456-977f-11e9-2de3-97ff7677985e"

[compat]
PowerModelsDistribution = "0.16.0"
julia = "1.11.7"
